// ============================================================
// Mock data, Goals-First prototype
// ============================================================

const GOALS = [
  // ---- 3 OOTB default goals (auto-created when AI is enabled in the org) ----
  {
    id: "default-csat",
    name: "Increase CSAT",
    description: "Lift average CSAT across all AI-handled conversations.",
    audience: "AIC",
    isDefault: true,
    owner: "System",
    state: "live",
    progress: 78,
    target: { value: 4.6, unit: "score", direction: "increase", window: "Ongoing" },
    deltaPct: 4,
    trend: "up",
    points: [4.1, 4.15, 4.18, 4.2, 4.22, 4.25, 4.28, 4.3, 4.32, 4.34],
    topics: ["All AI-handled conversations"],
    coverage: { topics: "n/a", volume: "100%", deflectable: 0 },
    attached: {
      automations: [],
      monitors: [{ name: "AI-Generated CSAT", score: 0.86, status: "live" }],
      humanWorkflows: [],
      blocks: { procedures: 0, kb: 0, tools: 0, guardrails: 0 },
    },
    activity: [{ when: "On AI enablement", what: "Default goal seeded with AI activation" }],
  },
  {
    id: "default-sentiment",
    name: "Improve Customer Sentiment",
    description: "Track and improve sentiment trajectory across customer conversations.",
    audience: "AIC",
    isDefault: true,
    owner: "System",
    state: "live",
    progress: 62,
    target: { value: 15, unit: "%", direction: "increase", window: "Ongoing" },
    deltaPct: 6,
    trend: "up",
    points: [50, 51, 52, 53, 54, 56, 58, 60, 61, 62],
    topics: ["All conversations"],
    coverage: { topics: "n/a", volume: "100%", deflectable: 0 },
    attached: {
      automations: [],
      monitors: [{ name: "Sentiment trajectory", score: 0.74, status: "live" }],
      humanWorkflows: [],
      blocks: { procedures: 0, kb: 0, tools: 0, guardrails: 0 },
    },
    activity: [{ when: "On AI enablement", what: "Default goal seeded with AI activation" }],
  },
  {
    id: "default-nrr",
    name: "Improve Net Retention",
    description: "Track Net Retention Rate (NRR) across renewal and expansion conversations.",
    audience: "AIC",
    isDefault: true,
    owner: "System",
    state: "live",
    progress: 71,
    target: { value: 112, unit: "%", direction: "increase", window: "Annual" },
    deltaPct: 3,
    trend: "up",
    points: [106, 107, 107, 108, 108, 109, 109, 110, 110, 111],
    topics: ["Renewals", "Expansion"],
    coverage: { topics: "n/a", volume: "12%", deflectable: 0 },
    attached: {
      automations: [],
      monitors: [],
      humanWorkflows: [],
      blocks: { procedures: 0, kb: 0, tools: 0, guardrails: 0 },
    },
    activity: [{ when: "On AI enablement", what: "Default goal seeded with AI activation" }],
  },
  // ---- Custom goals (user-created) ----
  {
    id: "refund-20",
    name: "Reduce refund tickets by 20%",
    description: "Cut refund-related ticket volume across all channels by Q3.",
    audience: "AIC",
    owner: "Amisha Sharma",
    state: "live",
    target: { value: -20, unit: "%", direction: "decrease", window: "90 days" },
    progress: 71,
    deltaPct: -14,
    trend: "up",
    points: [0, -2, -3, -5, -7, -8, -10, -12, -13, -14],
    topics: ["Returns & refunds", "Refund order", "Cancel subscription"],
    coverage: { topics: "3 of 5", volume: "54%", deflectable: 75 },
    attached: {
      automations: [{ name: "Refund Order", version: "v3", status: "live" }],
      monitors: [{ name: "Refund eligibility check", score: 0.62, status: "attention" }],
      humanWorkflows: [{ name: "Damaged items escalation" }],
      blocks: { procedures: 3, kb: 2, tools: 4, guardrails: 1 },
    },
    activity: [
      { when: "2h ago", what: "Suggestion drafted: Suggest an upsell before applying a coupon code" },
      { when: "1d ago", what: "Drift alert: Damaged items, last 24h" },
      { when: "3d ago", what: "+1 procedure attached: Process Return or Refund" },
    ],
  },
  {
    id: "csat-46",
    name: "Improve CSAT to 4.6",
    description: "Lift average customer satisfaction across AIR-assisted conversations.",
    audience: "AIR",
    owner: "Amisha Sharma",
    state: "testing",
    target: { value: 4.6, unit: "score", direction: "increase", window: "90 days" },
    progress: 42,
    deltaPct: 8,
    trend: "up",
    points: [4.2, 4.21, 4.23, 4.24, 4.26, 4.28, 4.29, 4.31, 4.32, 4.34],
    topics: ["Product questions", "Account & login"],
    coverage: { topics: "2 of 5", volume: "21%", deflectable: 40 },
    attached: {
      automations: [{ name: "Copilot, Tier 1", version: "v1", status: "testing" }],
      monitors: [{ name: "AI-Generated CSAT", score: 0.86, status: "live" }],
      humanWorkflows: [],
      blocks: { procedures: 0, kb: 4, tools: 0, guardrails: 0 },
    },
    activity: [],
  },
  {
    id: "renewals-80",
    name: "Save at-risk renewals 80%",
    description: "Identify renewal risk early and convert to saves before lapse.",
    audience: "AIC+AIR",
    owner: "Priya Iyer",
    state: "attention",
    target: { value: 80, unit: "%", direction: "increase", window: "120 days" },
    progress: 31,
    deltaPct: -3,
    trend: "down",
    points: [42, 40, 38, 35, 33, 30, 28, 27, 29, 31],
    topics: ["Cancel subscription", "Billing"],
    coverage: { topics: "2 of 5", volume: "12%", deflectable: 30 },
    attached: {
      automations: [{ name: "Renewal Risk", version: "v2", status: "live" }],
      monitors: [{ name: "Save attempts", score: 0.41, status: "attention" }],
      humanWorkflows: [{ name: "Hand-off to retention" }],
      blocks: { procedures: 2, kb: 1, tools: 2, guardrails: 0 },
    },
    activity: [],
  },
  {
    id: "order-tracking",
    name: "Auto-resolve order tracking",
    description: "Fully deflect routine \"where is my order?\" questions.",
    audience: "AIC",
    owner: "Maria Lopez",
    state: "live",
    target: { value: -50, unit: "%", direction: "decrease", window: "60 days" },
    progress: 62,
    deltaPct: -28,
    trend: "up",
    points: [0, -5, -8, -12, -16, -19, -22, -24, -26, -28],
    topics: ["Order tracking", "Shipping delays"],
    coverage: { topics: "2 of 5", volume: "32%", deflectable: 92 },
    attached: {
      automations: [{ name: "Order Tracking", version: "v4", status: "live" }],
      monitors: [{ name: "Tracking deflection", score: 0.88, status: "live" }],
      humanWorkflows: [],
      blocks: { procedures: 2, kb: 2, tools: 3, guardrails: 0 },
    },
    activity: [],
  },
  {
    id: "frt-90s",
    name: "Cut first reply time to 90s",
    description: "Reduce average first reply time on the human-rep team to 90 seconds.",
    audience: "Human Reps",
    owner: "Jordan Lee",
    state: "live",
    target: { value: 90, unit: "seconds", direction: "decrease", window: "60 days" },
    progress: 74,
    deltaPct: -32,
    trend: "up",
    points: [150, 140, 134, 128, 121, 115, 108, 102, 98, 94],
    topics: ["Product questions", "Order tracking"],
    coverage: { topics: "2 of 5", volume: "28%", deflectable: 0 },
    attached: { automations: [], monitors: [{ name: "Team A FRT scorecard", score: 0.74, status: "live" }], humanWorkflows: [], blocks: { procedures: 0, kb: 0, tools: 0, guardrails: 0 } },
    activity: [],
  },
  {
    id: "nrr-112",
    name: "NRR to 112%",
    description: "Lift net revenue retention through expansion + churn reduction.",
    audience: "Sales",
    owner: "Mike Tran",
    state: "testing",
    target: { value: 112, unit: "%", direction: "increase", window: "annual" },
    progress: 35,
    deltaPct: 2,
    trend: "flat",
    points: [104, 104, 105, 105, 106, 106, 106, 107, 107, 108],
    topics: ["Renewal", "Expansion"],
    coverage: { topics: "2 of 5", volume: ",", deflectable: 0 },
    attached: { automations: [], monitors: [{ name: "Renewal pipeline health", score: 0.35, status: "testing" }], humanWorkflows: [], blocks: { procedures: 0, kb: 0, tools: 0, guardrails: 0 } },
    activity: [],
  },
];

const AUDIENCES = [
  { id: "all", label: "All" },
  { id: "AIC", label: "Customer AI" },
  { id: "AIR", label: "Rep AI" },
  { id: "Human Reps", label: "Human Reps" },
  { id: "Other", label: "Other" },
];

const STATES = [
  { id: "all", label: "All" },
  { id: "live", label: "Live", className: "live" },
  { id: "testing", label: "Testing", className: "testing" },
  { id: "attention", label: "Needs attention", className: "attention" },
  { id: "draft", label: "Draft", className: "draft" },
];

const COMPANY_PROFILE_DEFAULTS = {
  name: "Acme Outdoors",
  industry: "Retail & E-commerce",
  domain: "acmeoutdoors.com",
  brands: 2,
  channels: ["Email", "Chat", "SMS", "Instagram"],
  description:
    "Acme Outdoors sells outdoor and adventure gear direct-to-consumer through our online store and three flagship retail locations. We support customers across email, chat, SMS, and Instagram.",
};

const TOPICS = [
  { id: "returns", label: "Returns & refunds", volume: 18, aht: "5.8m", attached: true },
  { id: "refund-order", label: "Refund order", volume: 9, aht: "4.2m", attached: true },
  { id: "cancel-sub", label: "Cancel subscription", volume: 6, aht: "3.4m", attached: true },
  { id: "tracking", label: "Order tracking", volume: 24, aht: "3.2m" },
  { id: "product", label: "Product questions", volume: 12, aht: "2.4m" },
  { id: "account", label: "Account & login", volume: 9, aht: "4.1m" },
  { id: "shipping", label: "Shipping delays", volume: 8, aht: "3.7m" },
  { id: "billing", label: "Billing", volume: 5, aht: "5.1m" },
];

const AUTOMATIONS = [
  {
    id: "refund-order",
    name: "Refund Order",
    audience: "AIC",
    version: "v3",
    status: "live",
    type: "Conversational",
    drives: ["Reduce refund tickets by 20%"],
    modified: "May 19",
    modifiedBy: "Amisha",
    topics: ["Returns & refunds", "Refund order"],
    attachedBlocks: { procedures: 3, kb: 2, tools: 4, guardrails: 1 },
    lastEval: { pass: 5, fail: 1, when: "May 18" },
    firstRunMode: false,
  },
  {
    id: "order-tracking",
    name: "Order Tracking",
    audience: "AIC",
    version: "v4",
    status: "live",
    type: "Conversational",
    drives: ["Auto-resolve order tracking"],
    modified: "May 15",
    modifiedBy: "Maria",
    topics: ["Order tracking"],
    attachedBlocks: { procedures: 2, kb: 2, tools: 3, guardrails: 0 },
    lastEval: { pass: 7, fail: 0, when: "May 14" },
    firstRunMode: false,
  },
  {
    id: "damaged-items",
    name: "Damaged Items",
    audience: "AIC",
    version: "v1 draft",
    status: "testing",
    type: "Conversational",
    drives: ["Reduce refund tickets by 20%"],
    modified: "May 20",
    modifiedBy: "Amisha",
    topics: ["Returns & refunds", "Refund order"],
    attachedBlocks: { procedures: 2, kb: 1, tools: 2, guardrails: 0 },
    lastEval: { pass: 3, fail: 2, when: "May 20" },
    firstRunMode: false,
  },
  {
    id: "cancel-sub",
    name: "Cancel Subscription",
    audience: "AIC",
    version: "v2",
    status: "live",
    type: "Conversational",
    drives: ["Save at-risk renewals 80%"],
    modified: "May 10",
    modifiedBy: "Priya",
    topics: ["Cancel subscription", "Billing"],
    attachedBlocks: { procedures: 2, kb: 1, tools: 2, guardrails: 0 },
    lastEval: { pass: 4, fail: 0, when: "May 9" },
    firstRunMode: false,
  },
  {
    id: "account-recovery",
    name: "Account Recovery",
    audience: "AIC",
    version: "v3",
    status: "attention",
    type: "Conversational",
    drives: [],
    modified: "May 12",
    modifiedBy: "Amisha",
    topics: ["Account & login"],
    attachedBlocks: { procedures: 1, kb: 0, tools: 1, guardrails: 0 },
    lastEval: { pass: 2, fail: 1, when: "May 11" },
    firstRunMode: false,
  },
  {
    id: "shipping-delays",
    name: "Shipping Delays",
    audience: "AIC",
    version: "v2",
    status: "live",
    type: "Conversational",
    drives: ["Auto-resolve order tracking"],
    modified: "May 9",
    modifiedBy: "Maria",
    topics: ["Shipping delays"],
    attachedBlocks: { procedures: 1, kb: 1, tools: 1, guardrails: 0 },
    lastEval: { pass: 3, fail: 0, when: "May 8" },
    firstRunMode: false,
  },
  {
    id: "product-questions",
    name: "Product Questions",
    audience: "AIC",
    version: "draft",
    status: "draft",
    type: "Conversational",
    drives: [],
    modified: "May 21",
    modifiedBy: "Amisha",
    topics: ["Product questions"],
    attachedBlocks: { procedures: 0, kb: 1, tools: 0, guardrails: 0 },
    lastEval: null,
    firstRunMode: true,
  },
  {
    id: "copilot-tier-1",
    name: "Copilot, Tier 1",
    audience: "AIR",
    version: "v1",
    status: "testing",
    type: "Rep Copilot",
    drives: ["Improve CSAT to 4.6", "Cut first reply time to 90s"],
    modified: "May 18",
    modifiedBy: "Jordan",
    topics: ["Product questions", "Order tracking", "Account & login"],
    attachedBlocks: { procedures: 0, kb: 4, tools: 0, guardrails: 0 },
    lastEval: { pass: 6, fail: 1, when: "May 17" },
    firstRunMode: false,
  },
];

const PROCEDURES = [
  {
    id: "proc-process-refund",
    name: "Process Return or Refund",
    whenToUse: "Customer requests a refund or return for an order placed within 60 days.",
    steps: [
      "Verify customer identity using order email + zip.",
      "Look up the order and confirm refund eligibility.",
      "If eligible and unused: full refund. Apply via @issue_refund.",
      "If used/opened: offer store credit at 110%.",
      "Confirm method and timing to the customer.",
    ],
    associations: { allAIC: false, allAIR: false, automations: ["refund-order"] },
    topics: ["Returns & refunds", "Refund order"],
  },
  {
    id: "proc-damaged",
    name: "Handle Damaged or Defective Item",
    whenToUse: "Customer reports their item arrived damaged, defective, or different from listing.",
    steps: [
      "Apologize and acknowledge the damage.",
      "Ask for photos via @request_attachments.",
      "Auto-approve a replacement when item value < $250.",
      "If value > $250, escalate to human queue with full context.",
    ],
    associations: { allAIC: false, allAIR: false, automations: ["refund-order", "damaged-items"] },
    topics: ["Returns & refunds"],
  },
  {
    id: "proc-vip-coupon",
    name: "Apply Coupon (VIP)",
    whenToUse: "Existing VIP customer requests a coupon code.",
    steps: [
      "Verify VIP tier with @lookup_loyalty.",
      "Apply coupon code via @apply_coupon_code.",
      "Send confirmation with expiry date.",
    ],
    associations: { allAIC: true, allAIR: false, automations: [] },
    topics: ["Billing", "Returns & refunds"],
  },
];

const TEST_CATEGORIES = [
  {
    id: "standard-refunds",
    name: "Standard Refund Requests",
    audience: ["AIC"],
    topics: ["Refund order"],
    samples: 6,
    status: "current",
    score: 0.92,
    lastRun: "2 hours ago",
  },
  {
    id: "damaged",
    name: "Damaged or Defective Items",
    audience: ["AIC"],
    topics: ["Returns & refunds", "Product questions"],
    samples: 4,
    status: "current",
    score: 0.23,
    lastRun: "2 hours ago",
  },
  {
    id: "late-delivery",
    name: "Late Delivery Refunds",
    audience: ["AIC"],
    topics: ["Shipping delays", "Refund order"],
    samples: 5,
    status: "current",
    score: 0.66,
    lastRun: "2 hours ago",
  },
  {
    id: "tracking",
    name: "Order Tracking & Status",
    audience: ["AIC", "AIR"],
    topics: ["Order tracking"],
    samples: 5,
    status: "current",
    score: 0.84,
    lastRun: "2 hours ago",
  },
  {
    id: "product",
    name: "Product Questions",
    audience: ["AIC"],
    topics: ["Product questions"],
    samples: 5,
    status: "current",
    score: 0.41,
    lastRun: "2 hours ago",
  },
  {
    id: "account",
    name: "Identity & Account Access",
    audience: ["AIC"],
    topics: ["Account & login"],
    samples: 3,
    status: "current",
    score: 0.45,
    lastRun: "2 hours ago",
  },
];

const SUGGESTIONS = [
  {
    id: "sug-upsell-coupon",
    title: "Suggest an upsell before applying a coupon code",
    source: "Procedure Adherence Monitor",
    status: "draft",
    confidence: 0.82,
    confidenceLabel: "High",
    goal: "Improve CSAT to 4.6",
    detectedAgo: "2 hours ago",
    target: { type: "procedure", id: "proc-vip-coupon", label: "VIP Coupon" },
    whyMatters: "Conversations where a coupon was issued had a CSAT of 3.4 vs. 4.2 for non-coupon sessions.",
    patternDetected:
      "33% of coupon requests come from customers who haven't reviewed related products. Adding a recommendation step before the coupon is applied could meaningfully increase satisfaction with minimal friction.",
    evidence: { count: 2, label: "2 conversations failing the same way" },
    before: `IF customer in VIP AND requests coupon\n  → apply_coupon_code()`,
    after: `IF customer in VIP AND requests coupon\n  → get_related_products(order_history)\n  → recommend_products(top_match)\n  IF customer declines\n  → apply_coupon_code()`,
  },
  {
    id: "sug-tighten-handoff",
    title: "Tighten escalation handoff protocol",
    source: "Procedure Adherence Monitor",
    status: "draft",
    confidence: 0.82,
    confidenceLabel: "High",
    goal: "Reduce AI cost per conversation",
    detectedAgo: "14 hours ago",
    target: { type: "procedure", id: "proc-process-refund", label: "Process Return or Refund" },
    whyMatters: "AI is escalating refund conversations 23% above target, suggesting the handoff threshold is too tight.",
    patternDetected: "Of the 89 escalations in the last 14 days, 41% had all the context AI needed to resolve autonomously.",
    evidence: { count: 41, label: "41 conversations with avoidable escalation" },
    before: `IF refund_amount > $50\n  → escalate_to_human()`,
    after: `IF refund_amount > $250\n  OR customer_tier = "VIP"\n  → escalate_to_human()\nELSE\n  → issue_refund()`,
  },
  {
    id: "sug-kb-international",
    title: "Update KB article: shipping policy for international orders",
    source: "AI-CSAT Monitor",
    status: "draft",
    confidence: 0.67,
    confidenceLabel: "Medium",
    goal: "Improve CSAT to 4.6",
    detectedAgo: "1 day ago",
    target: { type: "kb", id: "kb-shipping-international", label: "International Shipping" },
    whyMatters: "International customers have CSAT 0.8pt lower than domestic on tracking questions; the KB article hasn't been updated since 2024.",
    patternDetected: "62% of international tracking questions reference policy gaps the AI couldn't answer from the existing article.",
    evidence: { count: 31, label: "31 international tracking conversations" },
  },
  {
    id: "sug-warmer-escalation",
    title: "Apply tone guidance: warmer escalation language",
    source: "AI-CSAT Monitor",
    status: "draft",
    confidence: 0.51,
    confidenceLabel: "Low",
    goal: "Improve CSAT to 4.6",
    detectedAgo: "3 days ago",
    target: { type: "tone", id: "tone-escalation", label: "Escalation Tone" },
    whyMatters: "Escalation handoffs that use clinical language correlate with lower handoff CSAT.",
    patternDetected: "AI uses \"I am unable to assist with this\" 42% of the time on escalation, vs. softer phrasings 18% of the time.",
    evidence: { count: 18, label: "18 lower-CSAT handoffs" },
  },
  {
    id: "sug-calibrate",
    title: "Calibrate quarterly: refresh the scorer with 100 new human-labeled examples",
    source: "Procedure Adherence Monitor",
    status: "draft",
    confidence: 0.67,
    confidenceLabel: "Medium",
    goal: "Improve procedure adherence",
    detectedAgo: "5 hours ago",
    target: { type: "monitor", id: "mon-procedure", label: "Procedure Adherence Monitor" },
    whyMatters: "The monitor has been running on the same calibration set for 90 days. Drift detection sensitivity drops over time without re-calibration.",
    patternDetected: "Confidence intervals on the latest 100 evaluations are 18% wider than at calibration.",
    evidence: { count: 100, label: "100 evaluations since last calibration" },
  },
];

const CONVERSATIONS = [
  {
    id: "c-1",
    subject: "Help me with my subscription plan and other things related",
    snippet: "I'd like to change my subscription plan to the family one and add my brother…",
    customer: { name: "Daniel Karp", since: "Mar 2022" },
    automation: "Refund Order",
    customerJob: "Subscription change",
    topics: ["Cancel subscription"],
    audience: "AIC",
    when: "Mar 1, 2026 · 7:14 pm",
  },
  {
    id: "c-2",
    subject: "I want help with my subscription",
    snippet: "Got a new credit card and want to update billing info before next renewal…",
    customer: { name: "Yvonne Doll", since: "Jan 2024" },
    automation: "Refund Order",
    customerJob: "Subscription update",
    topics: ["Billing"],
    audience: "AIC",
    when: "Mar 1, 2026 · 5:21 pm",
  },
  {
    id: "c-3",
    subject: "Can you make me a human?",
    snippet: "talk to a real person",
    customer: { name: "Pranav S.", since: "Feb 2025" },
    automation: "Refund Order",
    customerJob: "Escalation",
    topics: ["Account & login"],
    audience: "AIC",
    when: "Mar 1, 2026 · 4:00 pm",
  },
  {
    id: "c-4",
    subject: "Hey, I think I need a refund for my Sansyou subscription, perhaps I missed it…",
    snippet: "Please, please process my refund, I cancelled last week.",
    customer: { name: "Ella Goldstein", since: "Aug 2023" },
    automation: "Refund Order",
    customerJob: "Refund request",
    topics: ["Refund order"],
    audience: "AIC",
    when: "Mar 1, 2026 · 1:32 pm",
    flagged: true,
  },
  {
    id: "c-5",
    subject: "Order #88732 hasn't shipped",
    snippet: "It's been 6 days since I placed my order…",
    customer: { name: "Marcus Webb", since: "Nov 2024" },
    automation: "Order Tracking",
    customerJob: "Shipping status",
    topics: ["Order tracking", "Shipping delays"],
    audience: "AIC",
    when: "Feb 28, 2026 · 10:14 am",
  },
];

const RAIL_SUGGESTED_PROMPTS = [
  "Add a step about VIP coupons",
  "Make the tone more conversational",
  "Add a guardrail against refunds > $250",
];

const ASSISTANT_INITIAL_MESSAGE = `Hi! I'm your build assistant. Ask me anything as you fill out this automation, drafting procedures, refining tone, suggesting guardrails, or what each section does.`;

window.MOCK = {
  GOALS,
  AUDIENCES,
  STATES,
  COMPANY_PROFILE_DEFAULTS,
  TOPICS,
  AUTOMATIONS,
  PROCEDURES,
  TEST_CATEGORIES,
  SUGGESTIONS,
  CONVERSATIONS,
  RAIL_SUGGESTED_PROMPTS,
  ASSISTANT_INITIAL_MESSAGE,
};
