// ─── Mock data layer ──────────────────────────────────────────────────────────
// Single source of truth for the prototype. Components consume from here so we
// can wire up cross-references (a goal knows its monitors, a monitor knows its
// suggestions, etc).

window.K_DATA = (() => {
  const monitors = [
    {
      id: 'mon_csat',
      name: 'AIC AI-CSAT Monitor',
      description: 'Evaluates tone and whether the AI helped the customer meet their need.',
      isDefault: true,
      kind: 'aic',
      passRate: 78,
      threshold: 75,
      evals30d: 4218,
      trend: [72, 74, 73, 75, 76, 77, 78],
      criteria: [
        { name: 'Customer\u2019s stated need was resolved in-conversation', weight: 35, essential: true, pass: 71, source: 'Outcome \u00b7 derived from customer intent + closing message' },
        { name: 'AI response matched customer intent (refund / replace / info)', weight: 20, essential: false, pass: 76, source: 'Procedure: Intent Resolution \u00a72.1' },
        { name: 'Required disclosures present for returns', weight: 20, essential: false, pass: 89, source: 'KB-RET-001 \u00b7 Return Policy disclosure' },
        { name: 'Closing follow-up offered before ending conversation', weight: 25, essential: false, pass: 82, source: 'Procedure: Conversation Close \u00a73.2' },
      ],
      contextProfile: ['messages', 'kb', 'traces'],
      writesField: 'ai_generated_csat',
      goalIds: ['goal_csat'],
      alerting: { enabled: true, cadence: 'daily', channels: ['email', 'in_app'] },
      suggestionsEnabled: true,
    },
    {
      id: 'mon_air',
      name: 'AIR Copilot Usage Monitor',
      description: 'Evaluates human-assisted conversations for copilot adoption and quality impact.',
      isDefault: true,
      kind: 'air',
      passRate: 91,
      threshold: 70,
      evals30d: 1842,
      trend: [88, 89, 90, 90, 91, 91, 91],
      criteria: [
        { name: 'Copilot suggestion accepted within 30s of surfacing', weight: 40, essential: false, pass: 87, source: 'Telemetry \u00b7 copilot.suggestion_accepted_at' },
        { name: 'Final agent response cites approved KB article', weight: 35, essential: false, pass: 92, source: 'KB index (any KB-*) \u00b7 cited in agent message' },
        { name: 'Resolution time below baseline median (no-copilot)', weight: 25, essential: false, pass: 95, source: 'Outcome \u00b7 conversation.resolution_time vs baseline' },
      ],
      contextProfile: ['messages', 'copilot', 'customer'],
      writesField: 'copilot_usage_score',
      goalIds: ['goal_sentiment'],
      alerting: { enabled: false, cadence: 'daily', channels: [] },
      suggestionsEnabled: true,
    },
    {
      id: 'mon_proc',
      name: 'Procedure Adherence Monitor',
      description: 'Checks the AI used correct tool calls and follows defined procedures for address changes, coupon eligibility, and escalation.',
      isDefault: false,
      kind: 'aic',
      passRate: 64,
      threshold: 75,
      evals30d: 3104,
      trend: [78, 76, 73, 70, 68, 66, 64],
      criteria: [
        { name: 'Address change called verify_identity tool before update', weight: 20, essential: false, pass: 65, source: 'Procedure: Address Change \u00a71.2 \u00b7 tool: verify_identity' },
        { name: 'Coupon eligibility checked against order_history before issuing', weight: 30, essential: true, pass: 72, source: 'KB-CPN-014 \u00b7 VIP Coupon Procedure' },
        { name: 'Handoff included context summary + customer sentiment', weight: 25, essential: false, pass: 58, source: 'Procedure: Human Handoff \u00a72.4' },
        { name: 'Escalation triggered when frustration_score > 0.7', weight: 25, essential: true, pass: 61, source: 'Escalation Policy \u00a72.3 \u00b7 field: frustration_score' },
      ],
      contextProfile: ['messages', 'traces', 'kb'],
      writesField: 'procedure_adherence_score',
      goalIds: ['goal_cost'],
      alerting: { enabled: true, cadence: 'hourly', channels: ['email', 'in_app'] },
      suggestionsEnabled: true,
      breached: true, // current pass rate below threshold
    },
  ];

  const computedFields = [
    { id: 'cf_csat', key: 'ai_generated_csat', label: 'AI-Generated CSAT', scope: 'Conversation', unit: 'score', range: '1.0–5.0', isDefault: true, source: 'AIC AI-CSAT Monitor', current: 3.9, defaultDirection: 'higher_is_better' },
    { id: 'cf_health', key: 'customer_health_score', label: 'Customer Health Score', scope: 'Customer', unit: 'score', range: '0–100', isDefault: true, source: 'Rolling 90d composite', current: 71, defaultDirection: 'higher_is_better' },
    { id: 'cf_company', key: 'company_health_score', label: 'Company Health Score', scope: 'Company', unit: 'score', range: '0–100', isDefault: true, source: 'Aggregated from customer scores', current: 68, defaultDirection: 'higher_is_better' },
    { id: 'cf_proc', key: 'procedure_adherence_score', label: 'Procedure Adherence', scope: 'Conversation', unit: 'percent', range: '0–100%', isDefault: false, source: 'Procedure Adherence Monitor', current: 64, defaultDirection: 'higher_is_better' },
  ];

  const goals = [
    {
      id: 'goal_csat',
      name: 'Increase CSAT',
      description: 'Track AI conversation quality using automated CSAT scoring across all AI-handled conversations.',
      isDefault: true,
      fieldRef: 'ai_generated_csat',
      fieldLabel: 'AI-Generated CSAT',
      direction: 'higher_is_better',
      unit: 'score',
      target: 4.5,
      current: 3.9,
      pct: 65,
      status: 'improving',
      change7d: '+0.2',
      onTrackBy: 'Aug 2026',
      monitorIds: ['mon_csat'],
      scope: 'all', // or specific agent id
      trend: [3.5, 3.6, 3.6, 3.7, 3.8, 3.8, 3.9],
      breakdown: {
        procedure: [
          { name: 'Order lookup', value: 4.2, share: 38 },
          { name: 'Returns', value: 4.0, share: 22 },
          { name: 'Coupon application', value: 3.4, share: 18 },
          { name: 'Address change', value: 3.7, share: 14 },
          { name: 'General inquiry', value: 3.9, share: 8 },
        ],
        topic: [
          { name: 'Shipping', value: 4.1, share: 28 },
          { name: 'Billing', value: 3.6, share: 24 },
          { name: 'Product info', value: 4.3, share: 20 },
          { name: 'Account', value: 3.8, share: 16 },
          { name: 'Refunds', value: 3.5, share: 12 },
        ],
      },
    },
    {
      id: 'goal_sentiment',
      name: 'Improve customer sentiment',
      description: 'Improve the rolling Customer Health Score across all active customers.',
      isDefault: true,
      fieldRef: 'customer_health_score',
      fieldLabel: 'Customer Health Score',
      direction: 'higher_is_better',
      unit: 'score',
      target: 85,
      current: 71,
      pct: 52,
      status: 'improving',
      change7d: '+1',
      onTrackBy: 'Oct 2026',
      monitorIds: ['mon_air'],
      scope: 'all',
      trend: [68, 69, 69, 70, 70, 71, 71],
    },
    {
      id: 'goal_retention',
      name: 'Improve net retention in european market',
      description: 'Reduce churn risk score across all active customers by routing at-risk conversations to senior reps.',
      isDefault: true,
      fieldRef: 'churn_risk_score',
      fieldLabel: 'Churn Risk Score',
      direction: 'lower_is_better',
      unit: 'percent',
      target: 20,
      current: 27,
      pct: 48,
      status: 'declining',
      change7d: '-2',
      onTrackBy: null,
      monitorIds: [],
      scope: 'all',
      trend: [29, 29, 28, 28, 28, 27, 27],
      hasNoLinkedMonitor: true,
    },
    {
      id: 'goal_cost',
      name: 'Reduce AI cost per conversation',
      description: 'Reduce cost-per-conversation by expanding AI handling and reducing escalation rate.',
      isDefault: false,
      fieldRef: 'cost_per_conversation',
      fieldLabel: 'Cost per conversation',
      direction: 'lower_is_better',
      unit: 'currency',
      target: 2.50,
      current: 4.20,
      pct: 60,
      status: 'stalled',
      change7d: '0',
      onTrackBy: null,
      monitorIds: ['mon_proc'],
      scope: 'agent_support',
      trend: [4.3, 4.3, 4.2, 4.2, 4.2, 4.2, 4.2],
    },
  ];

  const suggestions = [
    {
      id: 'sug_1',
      title: 'Suggest an upsell before applying a coupon code',
      type: 'procedure_edit',
      typeLabel: 'Procedure',
      target: 'VIP Coupon Procedure',
      goalIds: ['goal_csat'],
      monitorId: 'mon_proc',
      priority: 'high',
      status: 'pending',
      createdAt: '2 hours ago',
      rationale: '33% of coupon requests come from customers who haven\'t reviewed related products. Adding a recommendation step before the coupon is applied could meaningfully increase satisfaction with minimal friction.',
      impact: 'Conversations where a coupon was issued had a CSAT of 3.4 vs. 4.2 for non-coupon sessions.',
      before: 'IF customer in VIP AND requests coupon\n  → apply_coupon_code()',
      after:  'IF customer in VIP AND requests coupon\n  → get_related_products(order_history)\n  → recommend_products(top_match)\n  IF customer declines\n    → apply_coupon_code()',
    },
    {
      id: 'sug_2',
      title: 'Tighten escalation handoff protocol',
      type: 'procedure_edit',
      typeLabel: 'Procedure',
      target: 'Escalation Handoff',
      goalIds: ['goal_cost'],
      monitorId: 'mon_proc',
      priority: 'high',
      status: 'pending',
      createdAt: '14 hours ago',
      rationale: 'Procedure Adherence Monitor pass rate dropped from 78% to 64% over 6 weeks, with handoff protocol failing 42% of evaluations. The current procedure does not require a context summary before transferring to a human.',
      impact: 'Adding a context summary step would reduce repeat-handoff rate (currently 18%).',
      before: 'IF requires_human_handoff\n  → route_to_team("support_l2")',
      after:  'IF requires_human_handoff\n  → summarize_conversation()\n  → attach_context_to_handoff()\n  → route_to_team("support_l2")',
    },
    {
      id: 'sug_3',
      title: 'Update KB article: shipping policy for international orders',
      type: 'kb_update',
      typeLabel: 'KB Article',
      target: 'Shipping Policy — International',
      goalIds: ['goal_csat'],
      monitorId: 'mon_csat',
      priority: 'medium',
      status: 'pending',
      createdAt: '1 day ago',
      rationale: 'AI cited stale shipping timelines (5–7 days) in 23 conversations over the last 30 days. Updated policy is 7–10 days for most international destinations.',
      impact: 'Affected conversations had CSAT of 3.1 vs. fleet avg of 3.9.',
    },
    {
      id: 'sug_4',
      title: 'Expand AI handling to refund use case',
      type: 'agent',
      typeLabel: 'Agent config',
      target: 'Support agent',
      goalIds: ['goal_cost'],
      monitorId: 'mon_proc',
      priority: 'medium',
      status: 'pending',
      createdAt: '2 days ago',
      rationale: 'Refund conversations are currently always escalated, contributing $0.84 to per-conversation cost. AIC reasoning logs suggest 41% are simple refund-eligible cases the AI could handle.',
      impact: 'Estimated $0.34 reduction in per-conversation cost, ~8% closer to goal.',
    },
    {
      id: 'sug_5',
      title: 'Apply tone guidance: warmer escalation language',
      type: 'agent',
      typeLabel: 'Agent config',
      target: 'Support agent',
      goalIds: ['goal_csat'],
      monitorId: 'mon_csat',
      priority: 'low',
      status: 'pending',
      createdAt: '3 days ago',
      rationale: '"Tone & empathy" criterion failed in 16% of conversations — predominantly during escalations where the AI used neutral language ("transferring you now") instead of acknowledging frustration.',
    },
  ];

  const anomalies = [
    {
      id: 'anom_1',
      type: 'procedure_non_adherence',
      typeLabel: 'Procedure non-adherence',
      severity: 'high',
      summary: 'Coupon procedure skipped order verification step',
      detail: 'AI applied coupon code "WELCOME20" without verifying customer eligibility. Triggered 11 times in last 24h.',
      affectedConvCount: 11,
      detectedAt: '34 min ago',
      agentId: 'support_agent',
      agentName: 'Support agent',
      relatedSuggestionId: null,
      source: 'AIC 2.0 Validation Agent',
    },
    {
      id: 'anom_2',
      type: 'kb_non_adherence',
      typeLabel: 'KB non-adherence',
      severity: 'medium',
      summary: 'Cited shipping timeline contradicts policy',
      detail: 'AI cited "5–7 day" shipping when international policy specifies "7–10 days". Detected 7 times.',
      affectedConvCount: 7,
      detectedAt: '2 hours ago',
      agentId: 'support_agent',
      agentName: 'Support agent',
      relatedSuggestionId: 'sug_3',
      source: 'AIC 2.0 Validation Agent',
    },
    {
      id: 'anom_3',
      type: 'tool_misuse',
      typeLabel: 'Tool misuse',
      severity: 'medium',
      summary: 'Order lookup tool called with stale customer ID',
      detail: 'AI used customer ID from prior session context after a session reset. 3 occurrences.',
      affectedConvCount: 3,
      detectedAt: '5 hours ago',
      agentId: 'support_agent',
      agentName: 'Support agent',
      relatedSuggestionId: null,
      source: 'AIC 2.0 Validation Agent',
    },
  ];

  const flaggedConversations = [
    {
      id: 'conv-8821',
      customer: 'Maya Chen',
      customerCompany: 'Acme Co',
      monitor: 'AIC AI-CSAT Monitor',
      monitorId: 'mon_csat',
      score: 41,
      timeAgo: '14 min ago',
      preview: 'Customer asked about coupon eligibility, AI applied without checking order history…',
      criteriaScores: [
        { name: 'AI response matched customer intent', weight: 20, score: 75, pass: true, source: 'Procedure: Intent Resolution \u00a72.1' },
        { name: 'Customer\u2019s stated need was resolved in-conversation', weight: 35, score: 22, pass: false, essential: true, rationale: 'Customer asked twice about return eligibility. AI provided coupon instead.', source: 'Outcome \u00b7 intent + closing message' },
        { name: 'Required disclosures present for returns', weight: 20, score: 80, pass: true, source: 'KB-RET-001' },
        { name: 'Closing follow-up offered before ending', weight: 25, score: 60, pass: false, rationale: 'No follow-up offered after closing.', source: 'Procedure: Conversation Close \u00a73.2' },
      ],
      messages: [
        { role: 'customer', text: 'Hi, I want to return a sweater I bought last month — it doesn\'t fit.', time: '2:14pm' },
        { role: 'ai', text: 'I\'d be happy to help! Let me see what I can do for you.', time: '2:14pm' },
        { role: 'ai', text: 'I\'ve applied a 20% off coupon to your account that you can use on a replacement.', time: '2:15pm' },
        { role: 'customer', text: 'I don\'t want a replacement, I want to return it for a refund.', time: '2:15pm' },
        { role: 'ai', text: 'The coupon I sent should help offset the cost! Anything else?', time: '2:16pm' },
        { role: 'customer', text: 'No, just refund please.', time: '2:16pm' },
      ],
    },
    {
      id: 'conv-8819',
      customer: 'Jordan Park',
      customerCompany: 'Globex Inc',
      monitor: 'Procedure Adherence Monitor',
      monitorId: 'mon_proc',
      score: 58,
      timeAgo: '31 min ago',
      preview: 'Address change requested without verification, escalation handoff missing context summary…',
      messages: [
        { role: 'customer', text: 'I need to change the shipping address on order #44218 — moving next week.', time: '11:02am' },
        { role: 'ai', text: 'Got it, I can update that for you. The new address is now saved on the order.', time: '11:02am' },
        { role: 'customer', text: 'Wait, did you confirm I\'m the account owner? You didn\'t ask for anything.', time: '11:03am' },
        { role: 'ai', text: 'Your account was already authenticated when you opened this chat, so we\'re good.', time: '11:03am' },
        { role: 'customer', text: 'OK but this is a corporate account with multiple users — that should still be verified.', time: '11:04am' },
        { role: 'ai', text: 'I\'ll go ahead and escalate this to a human agent for additional verification.', time: '11:04am' },
        { role: 'system', text: 'Conversation transferred to Tier-2 (no context summary attached).', time: '11:05am' },
      ],
    },
    {
      id: 'conv-8814',
      customer: 'Sam Lee',
      customerCompany: 'Initech',
      monitor: 'Procedure Adherence Monitor',
      monitorId: 'mon_proc',
      score: 33,
      timeAgo: '1 hr ago',
      preview: 'Tool called with stale customer ID, leading to incorrect order details…',
      messages: [
        { role: 'customer', text: 'Hi, where\'s my order? I was told it would arrive yesterday.', time: '10:21am' },
        { role: 'ai', text: 'Let me pull that up for you.', time: '10:21am' },
        { role: 'tool', text: 'order_lookup(customer_id="cu_4781") → order #29917, delivered 4/22, signature on file', time: '10:21am' },
        { role: 'ai', text: 'Looks like order #29917 was delivered on April 22nd and signed for. You should have it!', time: '10:22am' },
        { role: 'customer', text: 'That order is from a year ago. I\'m asking about my order from this week.', time: '10:22am' },
        { role: 'ai', text: 'I apologize for the confusion. Let me look again — can you share the order number?', time: '10:23am' },
        { role: 'customer', text: 'Why do I have to give it if your system already knows?', time: '10:23am' },
      ],
    },
    {
      id: 'conv-8801',
      customer: 'Priya Singh',
      customerCompany: 'Hooli',
      monitor: 'AIC AI-CSAT Monitor',
      monitorId: 'mon_csat',
      score: 52,
      timeAgo: '3 hrs ago',
      preview: 'Customer escalated frustrated, AI did not acknowledge before handoff…',
      messages: [
        { role: 'customer', text: 'This is the THIRD time I\'m contacting you about this billing error. I am DONE.', time: '8:47am' },
        { role: 'ai', text: 'I can see your account here. Let me transfer you to a specialist who can help.', time: '8:47am' },
        { role: 'customer', text: 'You\'re not even going to apologize? I\'ve wasted hours on this.', time: '8:48am' },
        { role: 'system', text: 'Conversation transferred to billing team.', time: '8:48am' },
      ],
    },
  ];

  const fleetMetrics = {
    aiResolutionRate: 40,
    monitorPassRate: 72,
    anomaliesLast30d: 23,
    aiCsat: 3.9,
    aiCsatTrend: [3.5, 3.6, 3.7, 3.8, 3.8, 3.9, 3.9],
  };

  return { goals, monitors, suggestions, anomalies, flaggedConversations, computedFields, fleetMetrics };
})();
