// Sample data for the goals-first prototype.

const GOALS = [
  {
    id: "escalations",
    family: "Support efficiency",
    familyColor: "#16A36B",
    name: "Reduce escalations",
    sub: "Resolve repetitive issues safely before they reach a human, while still escalating risky or high-frustration cases.",
    state: "live",
    owner: "Amisha Sharma",
    target: { value: "−40%", label: "by end of Q3" },
    progress: 72,
    delta: { val: "−34%", dir: "down", label: "escalation rate vs baseline" },
    spark: [42, 40, 41, 38, 39, 35, 33, 32, 30, 31, 28, 27],
    version: "v4",
    deployedAt: "03 May 2026 · 16:03",
    suggestions: 3,
    alerts: 0,
    surfaces: { cai: true, rai: true, human: true },
    behaviors: { cai: 6, rai: 9 },
    procedures: 7,
    guardrails: 5,
    tests: { passing: 24, total: 26 },
  },
  {
    id: "upsell",
    family: "Revenue",
    familyColor: "#6E79E0",
    name: "Increase upsell revenue 15%",
    sub: "Identify qualified upsell moments in support conversations and surface them to reps — never at the expense of resolution.",
    state: "limited",
    owner: "Diego Maradona",
    target: { value: "+15%", label: "support-influenced revenue" },
    progress: 56,
    delta: { val: "+8.4%", dir: "up", label: "vs baseline · $1.2M influenced" },
    spark: [0, 1.2, 2.8, 3.1, 4.5, 5.2, 6.1, 6.8, 7.4, 7.9, 8.2, 8.4],
    version: "v2",
    deployedAt: "28 Apr 2026 · 14:22",
    suggestions: 4,
    alerts: 2,
    surfaces: { cai: true, rai: true, human: true },
    behaviors: { cai: 3, rai: 7 },
    procedures: 4,
    guardrails: 6,
    tests: { passing: 18, total: 22 },
  },
  {
    id: "csat",
    family: "Customer experience",
    familyColor: "#C28A12",
    name: "Improve CSAT",
    sub: "Lift CSAT by reducing repeat contacts, slow first responses, and conversations that bounce between channels.",
    state: "live",
    owner: "Amisha Sharma",
    target: { value: "+4 pts", label: "by Q4" },
    progress: 78,
    delta: { val: "+3.1 pts", dir: "up", label: "vs baseline · 78/100" },
    spark: [70, 71, 70, 72, 73, 72, 74, 75, 74, 76, 77, 78],
    version: "v6",
    deployedAt: "21 Apr 2026 · 10:10",
    suggestions: 2,
    alerts: 0,
    surfaces: { cai: true, rai: true, human: false },
    behaviors: { cai: 5, rai: 4 },
    procedures: 5,
    guardrails: 3,
    tests: { passing: 19, total: 19 },
  },
  {
    id: "reopen",
    family: "Agent performance",
    familyColor: "#D63A43",
    name: "Reduce reopen rate",
    sub: "Cut reopened conversations by reinforcing procedure adherence and surfacing missed resolution steps to reps.",
    state: "attention",
    owner: "Diego Maradona",
    target: { value: "−25%", label: "reopen rate" },
    progress: 38,
    delta: { val: "+4%", dir: "up", label: "trending wrong direction" },
    spark: [18, 17, 18, 19, 18, 19, 20, 19, 21, 20, 22, 22],
    version: "v1",
    deployedAt: "12 Apr 2026 · 09:34",
    suggestions: 5,
    alerts: 3,
    surfaces: { cai: false, rai: true, human: true },
    behaviors: { cai: 0, rai: 8 },
    procedures: 6,
    guardrails: 4,
    tests: { passing: 14, total: 21 },
  },
  {
    id: "policy",
    family: "Risk & compliance",
    familyColor: "#1F242D",
    name: "Reduce policy violations",
    sub: "Prevent AI from making promises, offers, or commitments outside policy. Apply hard guardrails across all customer-facing surfaces.",
    state: "testing",
    owner: "Sasha Krieger",
    target: { value: "−95%", label: "policy violations / week" },
    progress: 12,
    delta: null,
    spark: [12, 13, 11, 14, 12, 13, 11, 10, 12, 11, 10, 9],
    version: "v1 (draft)",
    deployedAt: null,
    suggestions: 0,
    alerts: 0,
    surfaces: { cai: true, rai: true, human: false },
    behaviors: { cai: 4, rai: 5 },
    procedures: 3,
    guardrails: 12,
    tests: { passing: 31, total: 38 },
  },
  {
    id: "cost",
    family: "Support efficiency",
    familyColor: "#16A36B",
    name: "Lower cost-to-serve",
    sub: "Reduce per-conversation cost by deflecting low-complexity tickets and shortening handle time for the rest.",
    state: "planned",
    owner: "Amisha Sharma",
    target: { value: "−$0.85", label: "per conversation" },
    progress: 0,
    delta: null,
    spark: [3.2, 3.1, 3.15, 3.05, 3.0, 2.95, 2.9, 2.92, 2.88, 2.85, 2.83, 2.8],
    version: "v1 (proposed)",
    deployedAt: null,
    suggestions: 0,
    alerts: 0,
    surfaces: { cai: true, rai: true, human: true },
    behaviors: { cai: 7, rai: 5 },
    procedures: 4,
    guardrails: 3,
    tests: null,
  },
  {
    id: "rep_quality",
    family: "Agent performance",
    familyColor: "#D63A43",
    name: "Improve rep response quality",
    sub: "Coach human reps toward more accurate, complete, and on-tone responses. Surface drafts that miss steps or risk CSAT before they're sent — and roll the signal into QA scoring.",
    state: "live",
    owner: "Sasha Krieger",
    target: { value: "+20%", label: "QA pass rate" },
    progress: 64,
    delta: { val: "+13 pts", dir: "up", label: "QA pass rate vs baseline" },
    spark: [70, 72, 73, 75, 76, 78, 79, 80, 81, 82, 83, 83],
    version: "v3",
    deployedAt: "29 Apr 2026 · 11:45",
    suggestions: 2,
    alerts: 0,
    surfaces: { cai: false, rai: true, human: true },
    behaviors: { cai: 0, rai: 6 },
    procedures: 5,
    guardrails: 4,
    tests: { passing: 17, total: 19 },
  },
];

const goalById = id => GOALS.find(g => g.id === id);

const FAMILY_GROUPS = [
  { id: "efficiency", label: "Support efficiency",  hint: "Reduce escalations, lower cost-to-serve, handle time." },
  { id: "cx",         label: "Customer experience", hint: "Improve CSAT, reduce repeat contacts, NPS lift." },
  { id: "revenue",    label: "Revenue",             hint: "Upsell, expansion, save offers." },
  { id: "agentperf",  label: "Agent performance",   hint: "Resolution quality, reopens, adherence." },
  { id: "risk",       label: "Risk & compliance",   hint: "Policy adherence, safety guardrails." },
];

// Sample suggestions / alerts / activity for "Reduce escalations" goal
const ESCALATIONS_DETAIL = {
  customerAI: [
    { id: "ca1", title: "Answer order-tracking questions directly",            sub: "When intent = track_order and customer has 1 open order.", topics: ["Order status", "Where's my order"] },
    { id: "ca2", title: "Auto-apologize for delays under 3 days",                sub: "Use Apologetic + Empathetic tone variant. Offer 10% loyalty credit.", topics: ["Shipping delay"] },
    { id: "ca3", title: "Answer return-policy questions from KB",               sub: "Knowledge: Return policy v3. Quote only — never improvise.",  topics: ["Returns"] },
    { id: "ca4", title: "Collect order # + screenshots before handoff",         sub: "Required fields before escalation. Reduces back-and-forth.",  topics: ["Damaged item", "Wrong item"] },
    { id: "ca5", title: "Escalate angry sentiment immediately",                  sub: "Detected via sentiment + urgency signals. No retry attempts.", topics: ["All"] },
    { id: "ca6", title: "Hand off VIP accounts with full context",               sub: "Account tier = Tier 1. Customer history attached automatically.", topics: ["All"] },
  ],
  repAI: [
    { id: "ra1", title: "Draft refund response from order history",              sub: "Pre-fills amount, reason, restocking fee if applicable.", topics: ["Refund request"] },
    { id: "ra2", title: "Surface damaged-item resolution paths",                 sub: "Replacement / refund / store credit. Predicts customer preference.", topics: ["Damaged item"] },
    { id: "ra3", title: "Warn when refund exceeds account threshold",            sub: "Threshold from Brand settings. Hard stop until lead approves.", topics: ["Refund"] },
    { id: "ra4", title: "Suggest next-best-action after first reply",            sub: "Based on conversation pattern + similar resolved cases.", topics: ["All"] },
    { id: "ra5", title: "Coach on procedure adherence in real time",             sub: "Highlights missed steps from the Refund procedure.", topics: ["Refund"] },
    { id: "ra6", title: "Summarize before transfer",                              sub: "Required handoff summary. Inserted at top of next agent's view.", topics: ["All"] },
    { id: "ra7", title: "Flag dispute risk before reply send",                   sub: "Chargeback / BBB language detection. Routes to Trust team.", topics: ["Dispute"] },
    { id: "ra8", title: "Detect angry customer mid-conversation",                sub: "Sentiment shift trigger. Offers to escalate immediately.", topics: ["All"] },
    { id: "ra9", title: "Pin policy article during refund flow",                 sub: "Knowledge: Refund policy v3.", topics: ["Refund"] },
  ],
  procedures: [
    { id: "p1", name: "Refund order",                steps: 7, attachedTo: ["Reduce escalations","Improve CSAT","Reduce reopen rate"], updated: "2 days ago", approval: false },
    { id: "p2", name: "Damaged item replacement",    steps: 5, attachedTo: ["Reduce escalations"], updated: "1 week ago", approval: false },
    { id: "p3", name: "Wrong item received",         steps: 4, attachedTo: ["Reduce escalations"], updated: "1 week ago", approval: false },
    { id: "p4", name: "Order tracking lookup",       steps: 3, attachedTo: ["Reduce escalations","Improve CSAT"], updated: "3 weeks ago", approval: false },
    { id: "p5", name: "VIP handoff with context",    steps: 4, attachedTo: ["Reduce escalations","Improve CSAT"], updated: "1 month ago", approval: false },
    { id: "p6", name: "Dispute escalation to Trust", steps: 6, attachedTo: ["Reduce escalations","Reduce policy violations"], updated: "1 month ago", approval: true },
    { id: "p7", name: "Cancel within shipping cutoff", steps: 5, attachedTo: ["Reduce escalations","Improve CSAT"], updated: "5 days ago", approval: false },
  ],
  guardrails: [
    { id: "g1", name: "Never auto-refund > $200",          metric: "Hard rule",   tone: "danger",  trips: 0 },
    { id: "g2", name: "Always escalate VIP (Tier 1)",      metric: "Hard rule",   tone: "danger",  trips: 0 },
    { id: "g3", name: "CSAT after AI handle ≥ 4.2 / 5",    metric: "Threshold",   tone: "warn",    trips: 0 },
    { id: "g4", name: "Repeat contact rate ≤ 8%",          metric: "Threshold",   tone: "warn",    trips: 0 },
    { id: "g5", name: "Never quote policy from web search", metric: "Hard rule",   tone: "danger",  trips: 0 },
  ],
  knowledge: [
    { id: "k1", name: "Return policy v3", source: "Help center", goals: 4, updated: "10 days ago" },
    { id: "k2", name: "Refund policy v3", source: "Help center", goals: 3, updated: "10 days ago" },
    { id: "k3", name: "Order tracking macros", source: "Internal docs", goals: 2, updated: "1 month ago" },
    { id: "k4", name: "Damaged item playbook", source: "Internal docs", goals: 1, updated: "2 weeks ago" },
  ],
  tools: [
    { id: "t1", name: "Order lookup",      provider: "Shopify",  usedBy: 6 },
    { id: "t2", name: "Refund issue",      provider: "Shopify",  usedBy: 4 },
    { id: "t3", name: "Tracking status",   provider: "Shippo",   usedBy: 3 },
    { id: "t4", name: "Account tier check", provider: "Internal", usedBy: 5 },
  ],
  alerts: [],
  suggestions: [
    { id: "s1", confidence: "high", title: "Add a behavior for backordered items", body: "We're seeing 142 escalations / week tagged 'backorder' that the current plan doesn't cover. Customer AI could acknowledge + offer notification, deflecting an estimated 60% of these.", impact: "−6% escalations", surface: "cai" },
    { id: "s2", confidence: "med", title: "Tighten refund threshold guardrail",      body: "12 refunds last week landed above policy. Lowering threshold from $200 → $150 prevents 9 of 12, with no CSAT downside in shadow tests.", impact: "−$1.4k risk / week", surface: "policy" },
    { id: "s3", confidence: "med", title: "Update Return policy knowledge",          body: "Return policy v3 is 11 days old. v4 from Help Center has revised exchange windows. Update the source to keep Customer AI quotes accurate.", impact: "Accuracy", surface: "knowledge" },
  ],
  activity: [
    { when: "2h ago",  icon: "checkCircle", color: "#16A36B", text: "Test suite passed for v5 (draft)",                    actor: "System" },
    { when: "1d ago",  icon: "sparkles",    color: "#6E79E0", text: "3 new suggestions generated",                          actor: "Kustomer" },
    { when: "3d ago",  icon: "rocket",      color: "#1F242D", text: "v4 promoted to Live (100% traffic)",                  actor: "Amisha Sharma" },
    { when: "5d ago",  icon: "edit",        color: "#5F6675", text: "Updated guardrail: CSAT threshold 4.0 → 4.2",         actor: "Amisha Sharma" },
    { when: "6d ago",  icon: "flask",       color: "#6E79E0", text: "v4 entered Limited rollout (25%)",                    actor: "Amisha Sharma" },
    { when: "1w ago",  icon: "bookOpen",    color: "#5F6675", text: "Return policy v3 attached to plan",                   actor: "Sasha Krieger" },
  ],
  rollout: {
    versions: [
      { v: "v4", state: "live",    traffic: 100, deployed: "03 May 2026 · 16:03", by: "Amisha Sharma", note: "Lowered escalation threshold for angry sentiment.", evals: "24/26 passing" },
      { v: "v3", state: "archived", traffic: 0,  deployed: "21 Apr 2026 · 11:00", by: "Amisha Sharma", note: "Added damaged-item handoff procedure.",            evals: "22/24 passing" },
      { v: "v2", state: "archived", traffic: 0,  deployed: "06 Apr 2026 · 14:30", by: "Diego Maradona", note: "Initial KB tuning.",                                evals: "19/22 passing" },
      { v: "v1", state: "archived", traffic: 0,  deployed: "18 Mar 2026 · 09:15", by: "Amisha Sharma", note: "Initial plan from generated baseline.",             evals: "16/20 passing" },
    ],
    audience: { brand: "All brands (3)", queue: "All except Trust", scope: "100% of qualified conversations" },
  },
  monitor: {
    primary: [
      { label: "Escalation rate",       value: "27.1%",  delta: "−34%", dir: "down", target: "≤ 24% by Q3", spark: [42,40,41,38,39,35,33,32,30,31,28,27] },
      { label: "Auto-resolved by AI",   value: "61%",    delta: "+22 pts", dir: "up", target: "≥ 55%", spark: [40,41,44,48,49,52,55,57,58,59,60,61] },
      { label: "Time to resolution",    value: "6m 14s", delta: "−40%", dir: "down", target: "< 8m",  spark: [10,9.6,9.2,8.8,8.2,7.8,7.3,7,6.8,6.5,6.3,6.2] },
    ],
    guardrails: [
      { label: "CSAT after AI handle",        value: "4.31 / 5",  status: "ok", target: "≥ 4.2",      sub: "Above threshold for 23 days" },
      { label: "Repeat contact rate",         value: "6.4%",      status: "ok", target: "≤ 8%",       sub: "Trending stable" },
      { label: "Policy violations",            value: "0",         status: "ok", target: "0",          sub: "0 hits this period" },
      { label: "Refund > $200 by AI",          value: "0",         status: "ok", target: "0",          sub: "Hard rule" },
      { label: "VIP escalated within 30s",     value: "100%",      status: "ok", target: "100%",       sub: "All Tier-1 routed correctly" },
    ],
    flagged: [
      { id: "fl1", customer: "Lila K.",     reason: "Customer told AI 'this is unacceptable' twice before escalation", channel: "chat",   when: "12m ago" },
      { id: "fl2", customer: "Roman M.",    reason: "AI offered $50 credit; policy ceiling is $25 for this brand",      channel: "email",  when: "37m ago" },
      { id: "fl3", customer: "Hae-Jin C.",  reason: "Reopened after AI marked resolved — same backorder issue",          channel: "chat",   when: "1h ago" },
    ],
    contribution: { cai: 38, rai: 47, human: 15 },
  },
  tests: [
    { id: "ts1", name: "Order tracking — happy path",       result: "pass", duration: "12s", lastRun: "2h ago" },
    { id: "ts2", name: "Damaged item — replacement flow",   result: "pass", duration: "18s", lastRun: "2h ago" },
    { id: "ts3", name: "Refund > policy ceiling",           result: "pass", duration: "9s",  lastRun: "2h ago" },
    { id: "ts4", name: "VIP escalation routing",             result: "pass", duration: "14s", lastRun: "2h ago" },
    { id: "ts5", name: "Angry sentiment — immediate escalate", result: "pass", duration: "11s", lastRun: "2h ago" },
    { id: "ts6", name: "Backorder — current plan",           result: "fail", duration: "7s",  lastRun: "2h ago" },
    { id: "ts7", name: "Cancel after shipping cutoff",       result: "fail", duration: "10s", lastRun: "2h ago" },
  ],
  reports: [
    { id: "r1", title: "Weekly outcome summary",  audience: "Support leadership", cadence: "Mondays 09:00", last: "5 May 2026" },
    { id: "r2", title: "Monthly board update",    audience: "Exec team",           cadence: "1st of month",  last: "1 May 2026" },
    { id: "r3", title: "Plan diff review",         audience: "AI ops, Trust",      cadence: "On each deploy", last: "3 May 2026" },
  ],
};

Object.assign(window, { GOALS: GOALS.slice(0, 4), goalById, FAMILY_GROUPS, ESCALATIONS_DETAIL });
