// =============================================================
// Root App — state, routing, first-run trigger
// =============================================================

const FIRST_RUN_GOALS = []; // empty = first-run state
const NORMAL_GOALS    = window.GOALS;

const App = () => {
  // First-run toggle: when localStorage flag absent, start with no goals -> wizard auto-opens
  const [goals, setGoals] = React.useState(() => {
    return localStorage.getItem("kustomer.firstrun") === "done" ? NORMAL_GOALS : NORMAL_GOALS;
  });
  const [firstRun, setFirstRun]  = React.useState(false); // toggle for demo via tweak

  // Outer rail
  const [rail, setRail] = React.useState("ai");

  // Inner nav: "wizard" | "goals" | "performance" | "resources" | "connections" | "settings" | "advanced"
  const [nav, setNav] = React.useState("wizard");
  const [openGoalId, setOpenGoalId] = React.useState(null);

  // Sub-tabs per area
  const [perfTab, setPerfTab] = React.useState("dashboard");
  const [perfGoalFilter, setPerfGoalFilter] = React.useState(null);
  const [resTab, setResTab] = React.useState("procedures");
  const [setTab, setSetTab] = React.useState("aic");
  const [advTab, setAdvTab] = React.useState("automations");

  // Assistant
  const [assistantCollapsed, setAssistantCollapsed] = React.useState(false);
  const [assistantClosed, setAssistantClosed]       = React.useState(false);

  // Initial first-run check
  React.useEffect(() => {
    const reset = new URL(window.location.href).searchParams.get("firstrun");
    if (reset === "1") {
      setGoals([]);
      setFirstRun(true);
      setNav("wizard");
    }
  }, []);

  // When goals list is empty AND firstRun, wizard is the landing
  React.useEffect(() => {
    if (goals.length === 0 && firstRun) setNav("wizard");
  }, [goals.length, firstRun]);

  // ─ Navigation handler ─────────────────────────────────────
  const handleNav = (target) => {
    if (typeof target === "string") {
      setNav(target);
      setOpenGoalId(null);
    } else if (target && target.type === "goal") {
      setNav("goals");
      setOpenGoalId(target.id);
    }
  };

  const startWizard = () => {
    setNav("wizard");
    setOpenGoalId(null);
  };

  const completeWizard = (state) => {
    // One goal record per selected goal id
    const META = {
      deflect:  { name: "Reduce escalations",       family: "Support efficiency",  familyColor: "#16A36B" },
      csat:     { name: "Improve CSAT",             family: "Customer experience", familyColor: "#C28A12" },
      speed:    { name: "Speed up rep responses",   family: "Agent performance",   familyColor: "#D63A43" },
      tracking: { name: "Status & order tracking",  family: "Customer experience", familyColor: "#C28A12" },
      upsell:   { name: "Increase upsell revenue",  family: "Revenue",             familyColor: "#6E79E0" },
      policy:   { name: "Reduce policy violations", family: "Risk & compliance",   familyColor: "#1F242D" },
    };
    const now = Date.now();
    const newGoals = (state.goals.length ? state.goals : ["deflect"]).map((id, i) => {
      const m = META[id] || { name: "New goal", family: "Support efficiency", familyColor: "#16A36B" };
      return {
        id: `newgoal_${now}_${i}`,
        family: m.family, familyColor: m.familyColor,
        name: m.name,
        sub: "Auto-generated by Get Started wizard.",
        state: "limited", owner: "Amisha Sharma",
        target: { value: "TBD", label: "set after first week" },
        progress: 12, delta: null,
        spark: [0,1,2,3,4,5,6,7,8,7,8,9],
        version: "v1", deployedAt: "today",
        suggestions: 0, alerts: 0,
        surfaces: { cai: state.audience.includes("cai"), rai: state.audience.includes("rai"), human: true },
        behaviors: { cai: 6, rai: 4 },
        procedures: 7, guardrails: 5,
        tests: { passing: 5, total: 7 },
      };
    });
    setGoals(prev => {
      if (prev.length === 0) return [...newGoals, ...NORMAL_GOALS];
      return [...newGoals, ...prev];
    });
    localStorage.setItem("kustomer.firstrun", "done");
    setNav("goals");
    setOpenGoalId(newGoals[0].id);
  };

  // Jump from slide-out to other areas with goal filter
  const handleJump = (target, sub) => {
    if (target === "performance") {
      setPerfTab(sub || "dashboard");
      setPerfGoalFilter(openGoalId);
      setNav("performance");
      setOpenGoalId(null);
    } else if (target === "resources") {
      setResTab(sub || "procedures");
      setNav("resources");
      setOpenGoalId(null);
    }
  };

  // Assistant context
  const assistantContext =
    rail !== "ai" ? "off-ai" :
    nav === "wizard" ? "wizard" :
    openGoalId ? "goal" :
    nav === "goals" ? "goals-home" :
    nav;

  // ── Off-AI stub ─────────────────────────────────────────
  if (rail !== "ai") {
    return (
      <div style={{ display: "flex", height: "100vh" }}>
        <Rail active={rail} onChange={setRail}/>
        <div style={{ flex: 1, display: "flex", alignItems: "center", justifyContent: "center", background: "#fff" }}>
          <div style={{ textAlign: "center", color: T.ink3 }}>
            <Icon name="info" size={28} strokeWidth={1.7}/>
            <div style={{ fontSize: 16, fontWeight: 700, color: T.ink, marginTop: 12 }}>Outside this prototype</div>
            <div style={{ fontSize: 13, marginTop: 4 }}>Click <b style={{ color: T.ink }}>AI</b> in the rail to return.</div>
          </div>
        </div>
        <AssistantPanel context="off-ai" collapsed={assistantCollapsed} closed={assistantClosed} onToggle={() => setAssistantCollapsed(c => !c)} onClose={() => setAssistantClosed(true)} onOpen={() => { setAssistantClosed(false); setAssistantCollapsed(false); }}/>
      </div>
    );
  }

  // ── Main app shell ─────────────────────────────────────
  return (
    <div style={{ display: "flex", height: "100vh", overflow: "hidden" }}>
      <Rail active={rail} onChange={setRail}/>

      {/* NavSection is always visible, including during the wizard */}
      <NavSection
        nav={nav}
        openGoalId={openGoalId}
        onNav={handleNav}
        onStartWizard={startWizard}
        goals={goals}
        perfTab={perfTab}
        onPerfTab={(t) => {
          setPerfTab(t);
          setPerfGoalFilter(null);
          setNav("performance");
          setOpenGoalId(null);
        }}
        resTab={resTab}
        onResTab={(t) => {
          setResTab(t);
          setNav("resources");
          setOpenGoalId(null);
        }}
      />

      {/* Main content */}
      <main style={{ flex: 1, display: "flex", flexDirection: "column", overflow: "hidden", background: "#fff" }}>
        {nav === "wizard" && (
          <Wizard
            onCancel={() => { setNav(goals.length ? "goals" : "wizard"); }}
            onComplete={completeWizard}
          />
        )}

        {nav === "goals" && (
          <GoalsHome
            goals={goals}
            onOpenGoal={id => setOpenGoalId(id)}
            onStartWizard={startWizard}
          />
        )}

        {nav === "performance" && (
          <Performance
            subtab={perfTab} setSubtab={setPerfTab}
            goalFilter={perfGoalFilter} setGoalFilter={setPerfGoalFilter}
            goals={goals}
            onOpenGoal={id => { setNav("goals"); setOpenGoalId(id); }}
          />
        )}

        {nav === "resources" && (
          <Resources subtab={resTab} setSubtab={setResTab}/>
        )}

        {nav === "connections" && <Connections/>}

        {nav === "settings" && (
          <Settings subtab={setTab} setSubtab={setSetTab}/>
        )}

        {nav === "advanced" && (
          <Advanced subtab={advTab} setSubtab={setAdvTab}/>
        )}

        {nav.startsWith("adv-") && (
          <Advanced subtab={nav.replace("adv-","")} setSubtab={(s) => setNav("adv-" + s)}/>
        )}
      </main>

      <AssistantPanel context={assistantContext} collapsed={assistantCollapsed} closed={assistantClosed} onToggle={() => setAssistantCollapsed(c => !c)} onClose={() => setAssistantClosed(true)} onOpen={() => { setAssistantClosed(false); setAssistantCollapsed(false); }}/>

      {/* Goal slide-out overlays main column */}
      {openGoalId && (
        <GoalSlideout
          goal={goals.find(g => g.id === openGoalId)}
          onClose={() => setOpenGoalId(null)}
          onJump={handleJump}
        />
      )}

      {/* Tiny first-run reset utility (bottom-left) */}
      <button onClick={() => {
        localStorage.removeItem("kustomer.firstrun");
        setGoals([]);
        setNav("wizard");
      }} title="Reset to first-run (empty)" style={{
        position: "fixed", bottom: 12, left: 70,
        padding: "6px 10px", borderRadius: 999,
        background: "#fff", border: `1px solid ${T.rule}`,
        fontSize: 11, color: T.ink3, cursor: "pointer", zIndex: 30,
        fontFamily: "var(--font-sans)", fontWeight: 600,
      }}>↺ First-run state</button>
    </div>
  );
};

ReactDOM.createRoot(document.getElementById("app")).render(<App/>);
